import type { Quote, QuoteCategory } from "./types";

export const CATEGORY_LABEL: Record<QuoteCategory, string> = {
  idiom: "成语",
  verse: "诗句",
  aphorism: "名言",
  elegant: "雅词",
};

export const QUOTES: Quote[] = [
  {
    id: "mu-wu-quan-niu",
    text: "目无全牛",
    pinyin: "mù wú quán niú",
    meaning: "庖丁眼中不再是整头牛，而是肌理缝隙。技艺纯熟到看穿结构。",
    usage: "形容对一件事熟练到能一眼看见关键，而不是被整体吓住。",
    source: "《庄子·养生主》",
    category: "idiom",
  },
  {
    id: "ri-ri-xin",
    text: "日日新",
    pinyin: "rì rì xīn",
    meaning: "每一天都从旧里长出一点新。",
    usage: "写在日记或座右铭里，提醒自己不要用昨天的自己打发今天。",
    source: "《大学》引汤之盘铭",
    category: "aphorism",
  },
  {
    id: "hou-ji-bo-fa",
    text: "厚积薄发",
    pinyin: "hòu jī bó fā",
    meaning: "先把根扎深，再让锋芒出来。",
    usage: "适合描述长期练习、读书、写字——不是爆发，是蓄势。",
    source: "宋人论学常用",
    category: "idiom",
  },
  {
    id: "jing-yi-zhi-yuan",
    text: "静以志远",
    pinyin: "jìng yǐ zhì yuǎn",
    meaning: "心能静下来，志向才走得远。",
    usage: "提醒自己少被喧哗带走，把注意力放回长线。",
    source: "诸葛亮《诫子书》（常作「非宁静无以致远」）",
    category: "aphorism",
  },
  {
    id: "ruo-gu-ruo-chi",
    text: "若谷若虚",
    pinyin: "ruò gǔ ruò xū",
    meaning: "像山谷一样留空，才接得住新的东西。",
    usage: "学新词、听人说话时，先空出位置，再判断。",
    source: "《老子》「上德若谷」意",
    category: "elegant",
  },
  {
    id: "qing-feng-bu-shi",
    text: "清风不识字",
    pinyin: "qīng fēng bù shí zì",
    meaning: "风吹过书页，并不懂得上面写了什么。",
    usage: "自嘲读书时心不在焉，或调侃知识没有被真正消化。",
    source: "清人诗句化用",
    category: "verse",
  },
  {
    id: "xing-sheng-yu-si",
    text: "行胜于言",
    pinyin: "xíng shèng yú yán",
    meaning: "做完一件小事，胜过说十句打算。",
    usage: "打卡、落笔、出门走一圈，都是这句话的落地。",
    source: "古训常语",
    category: "aphorism",
  },
  {
    id: "bu-ji-bu-li",
    text: "不即不离",
    pinyin: "bù jí bù lí",
    meaning: "既不黏死，也不走开。刚刚好的距离。",
    usage: "谈习惯、谈关系、谈学习节奏，都可以用。",
    source: "佛典用语入文",
    category: "idiom",
  },
  {
    id: "wei-yan-da-yi",
    text: "微言大义",
    pinyin: "wēi yán dà yì",
    meaning: "很少的字，藏着很深的意思。",
    usage: "读短句、成语、古诗时，提醒自己慢一点品味。",
    source: "《汉书》论《春秋》",
    category: "idiom",
  },
  {
    id: "shan-shui-you-qing",
    text: "山水有清音",
    pinyin: "shān shuǐ yǒu qīng yīn",
    meaning: "山和水自己会发出清亮的声音。",
    usage: "写自然、写独处，或形容一件事本身已经足够动人。",
    source: "左思《招隐诗》",
    category: "verse",
  },
  {
    id: "zhi-zu-bu-ru",
    text: "知止不殆",
    pinyin: "zhī zhǐ bù dài",
    meaning: "知道何处该停，才不容易把自己耗尽。",
    usage: "习惯不是越多越好；选四件，做透，也是知止。",
    source: "《老子》",
    category: "aphorism",
  },
  {
    id: "han-quan-wu-xiang",
    text: "含章未央",
    pinyin: "hán zhāng wèi yāng",
    meaning: "才华含在里面，还没有全部绽开。",
    usage: "形容一个人正在积蓄，不必急着被看见。",
    source: "《易》「含章可贞」化用",
    category: "elegant",
  },
  {
    id: "ri-chu-er-zuo",
    text: "日出而作",
    pinyin: "rì chū ér zuò",
    meaning: "天亮了就开始做事。",
    usage: "不必和别人比谁更早，只跟自己的天亮对齐。",
    source: "古歌《击壤歌》",
    category: "verse",
  },
  {
    id: "wen-gu-zhi-xin",
    text: "温故知新",
    pinyin: "wēn gù zhī xīn",
    meaning: "把旧的再焐热一次，才会真正长出新的理解。",
    usage: "复习词句、重读一页书时最贴切。",
    source: "《论语·为政》",
    category: "idiom",
  },
  {
    id: "qian-xu-ruo-gu",
    text: "虚怀若谷",
    pinyin: "xū huái ruò gǔ",
    meaning: "胸怀空得像山谷，容得下不同的声音。",
    usage: "学表达时先听、先记，再组织自己的句子。",
    source: "《老子》意",
    category: "idiom",
  },
  {
    id: "mo-ran-kai-lang",
    text: "豁然开朗",
    pinyin: "huò rán kāi lǎng",
    meaning: "一下子看见了开阔处。",
    usage: "读懂一句难词、想通一件事后，可以这样说。",
    source: "陶渊明《桃花源记》",
    category: "idiom",
  },
  {
    id: "qing-huan-zi-zai",
    text: "清欢",
    pinyin: "qīng huān",
    meaning: "淡而真的快乐，不靠热闹撑着。",
    usage: "一杯茶、一页书、走一段路，都是清欢。",
    source: "苏轼「人间有味是清欢」",
    category: "elegant",
  },
  {
    id: "bu-yan-zhi-jiao",
    text: "君子之交淡如水",
    pinyin: "jūn zǐ zhī jiāo dàn rú shuǐ",
    meaning: "好的相交像水，清、稳、不黏。",
    usage: "谈友谊或合作时，强调长久比热烈更重要。",
    source: "《庄子·山木》",
    category: "aphorism",
  },
  {
    id: "zhi-xing-he-yi",
    text: "知行合一",
    pinyin: "zhī xíng hé yī",
    meaning: "知道了，就要在行动里把它做圆。",
    usage: "词句不只是收藏，读出声、写下来，才算合一。",
    source: "王阳明",
    category: "aphorism",
  },
  {
    id: "an-shi-er-shun",
    text: "安时处顺",
    pinyin: "ān shí chǔ shùn",
    meaning: "顺着此时能做的去做，不和时辰较劲。",
    usage: "早起失败也不自我审判，回到今天能完成的一格。",
    source: "《庄子·养生主》",
    category: "idiom",
  },
  {
    id: "luo-hua-wu-yan",
    text: "落花无言",
    pinyin: "luò huā wú yán",
    meaning: "花落下来，并不解释自己。",
    usage: "写含蓄、写结束，或形容一种不喧哗的完成。",
    source: "司空图《二十四诗品》",
    category: "verse",
  },
  {
    id: "xiao-yan-da-yi",
    text: "言近旨远",
    pinyin: "yán jìn zhǐ yuǎn",
    meaning: "话说得很近，意思走得很远。",
    usage: "练习表达时，用日常的句子说清楚深处的意思。",
    source: "《孟子》赵岐注用语",
    category: "idiom",
  },
  {
    id: "bu-qi-er-yu",
    text: "不期而遇",
    pinyin: "bù qī ér yù",
    meaning: "没约，却碰上了。",
    usage: "形容与一句话、一个人、一种天气的巧遇。",
    source: "常用书面语",
    category: "idiom",
  },
  {
    id: "shou-jing-ru-yu",
    text: "守静",
    pinyin: "shǒu jìng",
    meaning: "把心按住，让它停在一件事上。",
    usage: "晨读、落笔前，先守静一息。",
    source: "《老子》「守静笃」",
    category: "elegant",
  },
  {
    id: "xi-wei-yi-zhi",
    text: "千里之行，始于足下",
    pinyin: "qiān lǐ zhī xíng, shǐ yú zú xià",
    meaning: "再远的路，也是脚下这一步。",
    usage: "连续打卡的第一天、重新开始的那天，最适合。",
    source: "《老子》",
    category: "aphorism",
  },
  {
    id: "qing-tian-bai-ri",
    text: "光风霁月",
    pinyin: "guāng fēng jì yuè",
    meaning: "雨过天晴后的风和月亮，心地明净。",
    usage: "形容人品，或形容心情从浊变清。",
    source: "黄庭坚称周敦颐",
    category: "idiom",
  },
  {
    id: "du-shu-po-wan",
    text: "读书破万卷",
    pinyin: "dú shū pò wàn juàn",
    meaning: "读得足够多，下笔才会有底气。",
    usage: "鼓励晨读，但重点是「破」——真读进去，不是翻过。",
    source: "杜甫《奉赠韦左丞丈》",
    category: "verse",
  },
  {
    id: "xiao-yi-qing-xin",
    text: "洗心",
    pinyin: "xǐ xīn",
    meaning: "把心里积着的灰尘冲一冲。",
    usage: "散步、写三句、关掉屏幕，都可以叫洗心。",
    source: "《易·系辞》「圣人以此洗心」",
    category: "elegant",
  },
  {
    id: "zi-qiang-bu-xi",
    text: "自强不息",
    pinyin: "zì qiáng bù xī",
    meaning: "自己给自己力气，并且不停。",
    usage: "连续天数增加时，这句话比奖励更稳。",
    source: "《易·乾》",
    category: "aphorism",
  },
  {
    id: "dan-bo-ming-zhi",
    text: "淡泊明志",
    pinyin: "dàn bó míng zhì",
    meaning: "欲望淡一点，志向反而清楚。",
    usage: "习惯列表不要堆满；少而真，才看得见自己要去哪。",
    source: "诸葛亮《诫子书》",
    category: "aphorism",
  },
  {
    id: "chun-hua-qiu-shi",
    text: "春华秋实",
    pinyin: "chūn huá qiū shí",
    meaning: "春天开花，秋天结果。各有时辰。",
    usage: "现在还在「华」的阶段，不必急着要「实」。",
    source: "《汉书》意",
    category: "idiom",
  },
  {
    id: "yuan-fang-bu-jing",
    text: "优游",
    pinyin: "yōu yóu",
    meaning: "不紧不慢地走，心里仍有方向。",
    usage: "比「忙碌」更适合描述一种从容的学习状态。",
    source: "《诗经》「优哉游哉」",
    category: "elegant",
  },
  {
    id: "ju-sha-cheng-ta",
    text: "积微成著",
    pinyin: "jī wēi chéng zhù",
    meaning: "很小的事情堆起来，会变成看得见的形状。",
    usage: "每天一格、每天一句，正是积微。",
    source: "《荀子·乐论》近义",
    category: "idiom",
  },
  {
    id: "yue-luo-wu-ti",
    text: "月出惊山鸟",
    pinyin: "yuè chū jīng shān niǎo",
    meaning: "月亮出来，把山里的鸟都惊了一下。",
    usage: "写夜、写静，或形容一个轻微却清楚的触动。",
    source: "王维《鸟鸣涧》",
    category: "verse",
  },
  {
    id: "su-wei-zhi-xue",
    text: "素以为绚",
    pinyin: "sù yǐ wéi xuàn",
    meaning: "先有素底，颜色才显得好看。",
    usage: "表达先求清楚、朴素，再求华丽。",
    source: "《论语·八佾》",
    category: "elegant",
  },
  {
    id: "bu-wei-zao-nian",
    text: "欲速则不达",
    pinyin: "yù sù zé bù dá",
    meaning: "越想快，越走不到。",
    usage: "连续中断后重新开始，用这句话给自己减速。",
    source: "《论语·子路》",
    category: "aphorism",
  },
];

export function getQuote(id: string | null | undefined): Quote | undefined {
  if (!id) return undefined;
  return QUOTES.find((q) => q.id === id);
}

export function quotesByCategory(category: QuoteCategory | "all"): Quote[] {
  if (category === "all") return QUOTES;
  return QUOTES.filter((q) => q.category === category);
}

export function searchQuotes(query: string, pool = QUOTES): Quote[] {
  const q = query.trim().toLowerCase();
  if (!q) return pool;
  return pool.filter((item) =>
    [item.text, item.pinyin, item.meaning, item.usage, item.source]
      .join(" ")
      .toLowerCase()
      .includes(q),
  );
}
